
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: fhir-template
    container_name: fhir-template
    ports:
      - 32782:1972
      - 32783:52773
      - 32784:53773
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - ./data:/data
      - ./fhirUI:/usr/irissys/csp/fhirUI
    networks:
      - fhir-net

  triage:
    build:
      context: ./python/triage
      dockerfile: Dockerfile
    restart: always
    container_name: triage-app
    depends_on:
      - iris
      - ollama
    env_file:
      - ./python/triage/.env
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 7860:7860
    volumes:
      - ./python/triage:/app
    networks:
      - fhir-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
    entrypoint: ["sh", "-c", "ollama serve & sleep 5 && ollama pull qwen3.5:0.8b && wait"]
    networks:
      - fhir-net

networks:
  fhir-net:
    driver: bridge

volumes:
  ollama-data:
