
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: fhir-template
    container_name: fhir-template
    entrypoint: ["/home/irisowner/irisdev/custom-entrypoint.sh"]
    ports:
      - 32782:1972
      - 32783:52773
      - 32784:53773
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 7860:7860
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - ./data:/data
      - ./fhirUI:/usr/irissys/csp/fhirUI
      - ./:/home/irisowner/irisdev
